In [5]:
import geopandas as gpd
import pandas as pd
import os
from pathlib import Path

In [6]:
# Configuration 
BASE_DIR = Path.cwd().parent
RAW_DATA_DIR = os.path.join(BASE_DIR, "data", "raw")
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, "data", "processed")

SHAPEFILE_DIR = os.path.join(RAW_DATA_DIR, "RPG_2-2__SHP_LAMB93_R44_2023-01-01")
SHAPEFILE_PATH = os.path.join(SHAPEFILE_DIR, "PARCELLES_GRAPHIQUES.shp")
PARQUET_PATH = os.path.join(RAW_DATA_DIR, "RPG2023_sol_climat.parquet")
PRODUCTION_PATH = os.path.join(PROCESSED_DATA_DIR, "production_alsace.csv")
OUTPUT_PATH = os.path.join(PROCESSED_DATA_DIR, "vignes.geojson")

os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)

In [ ]:
print("Loading topographic data...")
topo = pd.read_parquet(PARQUET_PATH)
topo.head()

,id_parcel,com_parc,pct_com,dep_parc,reg_parc,alt_mean,alt_min,alt_max,pente_mean,expo_mean,...,stu_dom_1,smu_2,part_smu_2,stu_dom_2,smu_3,part_smu_3,stu_dom_3,smu_4,part_smu_4,stu_dom_4
0,1131984,01001,100.0,01,84,254.0,254.0,254.0,0.00,0.00,...,332298,None,0.0,None,None,0.0,None,None,0.0,None
1,1149764,01001,100.0,01,84,236.0,234.0,240.0,1.71,236.00,...,332298,None,0.0,None,None,0.0,None,None,0.0,None
2,1158497,01001,100.0,01,84,253.0,250.0,255.0,1.62,196.35,...,332298,None,0.0,None,None,0.0,None,None,0.0,None
3,1166357,01001,100.0,01,84,213.0,213.0,213.0,0.37,255.00,...,332298,None,0.0,None,None,0.0,None,None,0.0,None
4,1182569,01001,100.0,01,84,270.0,268.0,271.0,2.05,225.39,...,332298,None,0.0,None,None,0.0,None,None,0.0,None

In [8]:
print("Loading shapefile...")
geom = gpd.read_file(SHAPEFILE_PATH)
geom

Loading shapefile...

,ID_PARCEL,SURF_PARC,CODE_CULTU,CODE_GROUP,CULTURE_D1,CULTURE_D2,geometry
0,7,2.76,MIS,2,None,None,"POLYGON ((1045905.268 6811160.889, 1045903.688..."
1,8,24.33,BTN,24,None,None,"POLYGON ((787450.094 6837936.639, 787457.027 6..."
2,10,4.50,BTN,24,None,None,"POLYGON ((767897.131 6864296.736, 768542.204 6..."
3,11,3.48,BTH,1,DVN,DVS,"POLYGON ((1038562.699 6818438.69, 1038528.872 ..."
4,12,1.71,PPH,18,None,None,"POLYGON ((1074733.31 6884486.62, 1074739.32 68..."
...,...,...,...,...,...,...,...
853136,9866899,8.19,PPH,18,None,None,"POLYGON ((896231.61 6784309.27, 896196.268 678..."
853137,9866910,0.12,VRC,21,None,None,"POLYGON ((1027651.652 6807130.893, 1027642.578..."
853138,9866923,0.58,VRC,21,None,None,"POLYGON ((1029952.78 6838606.067, 1030031.097 ..."
853139,9866924,0.57,VRC,21,None,None,"POLYGON ((1020571.348 6781365.5, 1020573.593 6..."
853140,9866930,0.79,BTH,1,None,None,"POLYGON ((819934.521 6793734.234, 819927.082 6..."

In [9]:
# Merge
print("Merging datasets...")
merged = geom.merge(topo, left_on='ID_PARCEL', right_on='id_parcel', how='inner')
merged

Merging datasets...

,ID_PARCEL,SURF_PARC,CODE_CULTU,CODE_GROUP,CULTURE_D1,CULTURE_D2,geometry,id_parcel,com_parc,pct_com,...,stu_dom_1,smu_2,part_smu_2,stu_dom_2,smu_3,part_smu_3,stu_dom_3,smu_4,part_smu_4,stu_dom_4
0,7,2.76,MIS,2,None,None,"POLYGON ((1045905.268 6811160.889, 1045903.688...",7,67146,100.0,...,490281,None,0.00,None,None,0.0,None,None,0.0,None
1,8,24.33,BTN,24,None,None,"POLYGON ((787450.094 6837936.639, 787457.027 6...",8,10216,86.5,...,330429,None,0.00,None,None,0.0,None,None,0.0,None
2,10,4.50,BTN,24,None,None,"POLYGON ((767897.131 6864296.736, 768542.204 6...",10,51327,61.3,...,330429,None,0.00,None,None,0.0,None,None,0.0,None
3,11,3.48,BTH,1,DVN,DVS,"POLYGON ((1038562.699 6818438.69, 1038528.872 ...",11,67233,82.3,...,332381,None,0.00,None,None,0.0,None,None,0.0,None
4,12,1.71,PPH,18,None,None,"POLYGON ((1074733.31 6884486.62, 1074739.32 68...",12,67315,100.0,...,332381,None,0.00,None,None,0.0,None,None,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853136,9866899,8.19,PPH,18,None,None,"POLYGON ((896231.61 6784309.27, 896196.268 678...",9866899,52101,100.0,...,332364,None,0.00,None,None,0.0,None,None,0.0,None
853137,9866910,0.12,VRC,21,None,None,"POLYGON ((1027651.652 6807130.893, 1027642.578...",9866910,67445,100.0,...,330359,None,0.00,None,None,0.0,None,None,0.0,None
853138,9866923,0.58,VRC,21,None,None,"POLYGON ((1029952.78 6838606.067, 1030031.097 ...",9866923,67473,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None
853139,9866924,0.57,VRC,21,None,None,"POLYGON ((1020571.348 6781365.5, 1020573.593 6...",9866924,68365,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None
853140,9866930,0.79,BTH,1,None,None,"POLYGON ((819934.521 6793734.234, 819927.082 6...",9866930,10374,100.0,...,330348,330672,10.62,332429,None,0.0,None,None,0.0,None

In [10]:
# Filter vineyards
print("Filtering vineyards...")
vignes = merged[merged['CODE_CULTU'].isin(['VRC', 'VRT'])].copy()
vignes

Filtering vineyards...

,ID_PARCEL,SURF_PARC,CODE_CULTU,CODE_GROUP,CULTURE_D1,CULTURE_D2,geometry,id_parcel,com_parc,pct_com,...,stu_dom_1,smu_2,part_smu_2,stu_dom_2,smu_3,part_smu_3,stu_dom_3,smu_4,part_smu_4,stu_dom_4
11,69,2.76,VRC,21,None,None,"POLYGON ((796616.599 6770477.819, 796525.395 6...",69,10022,100.0,...,330618,330094,8.81,330348,None,0.0,None,None,0.0,None
16,136,0.09,VRC,21,None,None,"POLYGON ((764793.383 6918636.08, 764785.397 69...",136,51171,100.0,...,330415,None,0.00,None,None,0.0,None,None,0.0,None
19,186,0.07,VRC,21,None,None,"POLYGON ((1027167.526 6841830.474, 1027158.814...",186,67525,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None
54,564,0.45,VRC,21,None,None,"POLYGON ((748897.853 6887351.363, 748894.149 6...",564,51217,100.0,...,330453,None,0.00,None,None,0.0,None,None,0.0,None
58,598,0.07,VRC,21,None,None,"POLYGON ((1028338.26 6818497.782, 1028355.458 ...",598,67120,100.0,...,330400,None,0.00,None,None,0.0,None,None,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853093,9866411,0.04,VRC,21,None,None,"POLYGON ((1030197.509 6823260.077, 1030198.038...",9866411,67060,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None
853133,9866887,0.30,VRC,21,None,None,"POLYGON ((1019846.285 6795594.072, 1019832.263...",9866887,68147,100.0,...,330403,None,0.00,None,None,0.0,None,None,0.0,None
853137,9866910,0.12,VRC,21,None,None,"POLYGON ((1027651.652 6807130.893, 1027642.578...",9866910,67445,100.0,...,330359,None,0.00,None,None,0.0,None,None,0.0,None
853138,9866923,0.58,VRC,21,None,None,"POLYGON ((1029952.78 6838606.067, 1030031.097 ...",9866923,67473,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None
853139,9866924,0.57,VRC,21,None,None,"POLYGON ((1020571.348 6781365.5, 1020573.593 6...",9866924,68365,100.0,...,332378,None,0.00,None,None,0.0,None,None,0.0,None

In [13]:
vignes.columns

Index(['ID_PARCEL', 'SURF_PARC', 'CODE_CULTU', 'CODE_GROUP', 'CULTURE_D1',
       'CULTURE_D2', 'geometry', 'id_parcel', 'com_parc', 'pct_com',
       'dep_parc', 'reg_parc', 'alt_mean', 'alt_min', 'alt_max', 'pente_mean',
       'expo_mean', 'expo', 'mf_lambx', 'mf_lamby', 'mf_lambxy', 'mf_maille',
       'smu_1', 'part_smu_1', 'stu_dom_1', 'smu_2', 'part_smu_2', 'stu_dom_2',
       'smu_3', 'part_smu_3', 'stu_dom_3', 'smu_4', 'part_smu_4', 'stu_dom_4'],
      dtype='object')

In [16]:
SHAPEFILE_DIR2 = os.path.join(RAW_DATA_DIR, "2026-01-06-delim-parcellaire-aoc-shp")
SHAPEFILE_PATH2 = os.path.join(SHAPEFILE_DIR2, "2026-01-06_delim-parcellaire-aoc-shp.shp")

geom2 = gpd.read_file(SHAPEFILE_PATH2)
geom2

,dt,type_prod,categorie,type_denom,signe,id_app,app,id_denom,denom,insee,cvi,nomcom,insee2011,nomcom2011,id_aire,crinao,grp_name1,grp_name2,geometry
0,Angers,Vins,"Vin mousseux, Vin primeur, Vin tranquille",appellation,AOC,76,Anjou,173,Anjou,49002,"1B200, 1B200M 1, 1R200S, 1R203S, 1R203S01, 1S2...",ALLONNES,49002,ALLONNES,133,None,None,None,"MULTIPOLYGON (((476099.07 6692210.88, 476039.9..."
1,Angers,Vins,"Vin mousseux, Vin primeur, Vin tranquille",appellation,AOC,76,Anjou,173,Anjou,49003,"1B200, 1B200M 1, 1R200S, 1R203S, 1R203S01, 1S2...",TUFFALUN,"49003,49181,49230","AMBILLOU-CHATEAU,LOUERRE,NOYANT-LA-PLAINE",133,None,None,None,"MULTIPOLYGON (((445501.95 6686844.11, 445500.5..."
2,Angers,Vins,"Vin mousseux, Vin primeur, Vin tranquille",appellation,AOC,76,Anjou,173,Anjou,49007,"1B200, 1B200M 1, 1R200S, 1R203S, 1R203S01, 1S2...",ANGERS,49007,ANGERS,133,None,None,None,"MULTIPOLYGON (((430316.54 6711699.87, 430309.2..."
3,Angers,Vins,"Vin mousseux, Vin primeur, Vin tranquille",appellation,AOC,76,Anjou,173,Anjou,49011,"1B200, 1B200M 1, 1R200S, 1R203S, 1R203S01, 1S2...",ARTANNES-SUR-THOUET,49011,ARTANNES-SUR-THOUET,133,None,None,None,"MULTIPOLYGON (((464573.71 6682292.77, 464576.5..."
4,Angers,Vins,"Vin mousseux, Vin primeur, Vin tranquille",appellation,AOC,76,Anjou,173,Anjou,49012,"1B200, 1B200M 1, 1R200S, 1R203S, 1R203S01, 1S2...",AUBIGNE-SUR-LAYON,49012,AUBIGNE-SUR-LAYON,133,None,None,None,"MULTIPOLYGON (((436373.512 6685585.834, 436394..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11742,Valence,Vins,Vin tranquille,appellation,AOC,284,Saint-Joseph,1369,Saint-Joseph,42132,"1B545, 1R545",MALLEVAL,42132,MALLEVAL,1123,None,None,None,"MULTIPOLYGON (((834174.2 6477293.4, 834168.4 6..."
11743,Valence,Vins,Vin tranquille,appellation,AOC,284,Saint-Joseph,1369,Saint-Joseph,42272,"1B545, 1R545",Saint-Pierre-de-Bœuf,42272,SAINT-PIERRE-DE-BOEUF,1123,None,None,None,"MULTIPOLYGON (((836679.72 6475524.64, 836684.8..."
11744,Valence,Vins,"Vin mousseux, Vin tranquille",appellation,AOC,285,Saint-Péray,1370,Saint-Péray,07281,"1B546, 1B546M 1",SAINT-PERAY,07281,SAINT-PERAY,1124,None,None,None,"MULTIPOLYGON (((840647.467 6425782.393, 840640..."
11745,Valence,Vins,"Vin mousseux, Vin tranquille",appellation,AOC,285,Saint-Péray,1370,Saint-Péray,07323,"1B546, 1B546M 1",TOULAUD,07323,TOULAUD,1124,None,None,None,"MULTIPOLYGON (((843235.066 6426282.984, 843235..."
11746,Valence,Vins,Vin tranquille,appellation,AOC,1130,Vinsobres,2770,Vinsobres,26377,1R540S,VINSOBRES,26377,VINSOBRES,1742,None,None,None,"MULTIPOLYGON (((860488.29 6359537.58, 860423.6..."

In [20]:
geom2[0].geometry

KeyError: 0